name = "APipe"
uuid = "9a685650-ba06-11e9-13eb-e91c5df15e1f"
keywords = ["pipe", "function", "chaining", "macro"]
license = "MIT"
desc = "Abuse and Addict |> operators"
authors = ["aviatesk <aviatesk@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
